version: "3"
services:
  streamlit:
    build: .
    command: "streamlit run streamlit_app.py --server.headless=true --server.port=80"
    ports:
      - 80:80
    volumes:
      - ".:/usr/src/app/src"
