name: Daily update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install python3-dev -y
        sudo apt-get install libxml2-dev libxslt-dev -y
        sudo apt-get install libjpeg-dev zlib1g-dev libpng-dev -y
        pip install -r requirements.txt
        pip install -U --no-deps "dateparser>=1.0.0"
        pip install -U --no-deps "feedparser>=6.0.8"
        pip install sgmllib3k
        curl https://raw.githubusercontent.com/codelucas/newspaper/master/download_corpora.py | python3
    - name: Run daily update
      run: |
        python daily.py
        curl "https://gist.githubusercontent.com/Alyetama/be4c157f63ec538c8b62509b1961f0b0/raw/299d969aa1273c799889b72ff29b8d309625921e/fix_page_style.py" --output fix_page_style.py
        python fix_page_style.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        branch: gh-pages
        file_pattern: docs/**/*.html
