name: Job

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        bash fix_pip_packages.sh
        rm "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pygooglenews/__init__.py"
        curl "https://gist.githubusercontent.com/Alyetama/07af1ed69067d55e2721ae07ca60a1d6/raw/d2d68fcd40bb0343e3baa7fe05219b62bf82652c/__init__.py" --output "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pygooglenews/__init__.py"
        cat "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pygooglenews/__init__.py"

    - name: Run job.py
      env: 
        AZURE_POSTGRES_DB_STRING: ${{ secrets.AZURE_POSTGRES_DB_STRING }}
        BING_SEARCH_V7_SUBSCRIPTION_KEY: ${{ secrets.BING_SEARCH_V7_SUBSCRIPTION_KEY }}
        BING_SEARCH_V7_ENDPOINT: ${{ secrets.BING_SEARCH_V7_ENDPOINT }}
      run: |
        python job.py
